### ISSUE TITLE
Suggestion: Backport to 1.20.1

### ISSUE THREAD

**Issue by hyperdotbat** [Gsimken/Ticket-of-Eternal-Keep#1]
This mod seems very cool I do like the concept of conditional style keep inventory with a totem
If its not too much of a hassle, please backport to 1.20.1

**Comment by Gsimken** [comment]
Hey! I  will be backporting soon, thanks for the suggestions

**Comment by Gsimken** [comment]
@HaipaDev Uploaded in modrinth :)
https://modrinth.com/mod/ticket-of-eternal-keep/version/wGhy4wCl
Any issue just let me know it

**Comment by hyperdotbat** [comment]
Hey so I am just testing it, and im testing it in my big modpack
I see its an item kinda implemented like a datapack since its minecraft:paper
I can immediately tell you that for me it doesnt work, and there are couple of cuplrits; [Individual Keep Inv](https://modrinth.com/mod/individual-keep-inventory), [Keepinvcontrol](https://modrinth.com/mod/keep-inventory-control) and [Your Items Are Safe](https://modrinth.com/mod/your-items-are-safe)
But thats a given, those are multiple mods fighting over your stuff lol
I see that adding minecraft:paper to the whitelist of Keepinvcontrol does make it work properly tho

**Comment by Gsimken** [comment]
Thanks for the info, and Right the mod is implemented as a "plugin" for server the purporse of this is make it server side, with this the people can connect with vanilla clients and we can have more control than a datapack like use permissions with luckperms

I was investigating how I could make this mod compatible with the ones you mention, however, as they also modify the death event, it becomes almost impossible, from my side, I should modify the mods and get them to you if you want to make them compatible.

I will put a clarification regarding this in the mod description.

There is a bug with the "Gamerule KeepInventory true" and I appreciate that you reported it, I will correct it soon.

Remember that you can modify the item that is used for the ticket from the configuration file, with that it would lose the title but it would not be the role and it could be some unobtainable block.
